# Generated by Django 4.1.7 on 2023-04-17 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_addtocart_product_alter_cartitem_product'),
        ('account', '0003_alter_products_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='products',
        ),
    ]
