# Generated by Django 4.1.7 on 2023-04-18 11:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='wishlist_by',
            field=models.ManyToManyField(null=True, related_name='wish', to=settings.AUTH_USER_MODEL),
        ),
    ]
