# Generated by Django 4.1.7 on 2023-04-17 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_products'),
        ('customer', '0005_alter_addtocart_product_alter_cartitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtocart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.products'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.products'),
        ),
    ]
