# Generated by Django 4.1.7 on 2023-04-17 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_addtocart_product_alter_cartitem_product'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='products',
        ),
    ]
